
name: CI
on: [push, pull_request]
env:
  cache-version: v1
jobs:
  # test-and-build-windows:
  # build-qt5:
  #   strategy:
  #     matrix:
  #       platform: [windows-latest]
  #       qtversion: [5.14.1]
  #   runs-on: ${{ matrix.platform }}
  #   env:
  #     GOPATH: ${{ github.workspace }}
  #     GOROOT: ${{ github.workspace }}\go-root
  #     QT_VERSION: ${{ matrix.qtversion }}
  #     QT_DIR: ${{ github.workspace }}\Qt
  #     QT_MSYS2: true
  #     QT_MSYS2_DIR: D:\a\_temp\msys64\
  #     QT_MSVC: false
  #     QT_DEBUG: false
  #     GO111MODULE: off
  #     CGO_CFLAGS_ALLOW: ".*" 
  #     CGO_CXXFLAGS_ALLOW: ".*" 
  #     CGO_LDFLAGS_ALLOW: ".*" 
  #     #CGO_ENABLED: 1
  #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  #   steps:

  #   - name: Setup MSYS2 and install Qt5
  #     uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       msystem: mingw64
  #       install: mingw-w64-x86_64-toolchain
  #   - shell: msys2 {0}
  #     run: |
  #       pacman --noconfirm -S sed git mingw-w64-x86_64-toolchain mingw-w64-x86_64-python2
  #       git clone http://code.qt.io/qt/qt5.git D:\a\_temp\msys64\qt

  # test-and-build-windows:
  test-windows:
    strategy:
      matrix:
        platform: [windows-latest]
        qtversion: [5.14.1]
    runs-on: ${{ matrix.platform }}
    env:
      GOPATH: C:\
      GOROOT: C:\go-root
      QT_VERSION: ${{ matrix.qtversion }}
      # QT_DIR: ${{ github.workspace }}\Qt
      QT_API: 5.13.0
      QT_MSYS2: true
      QT_MSYS2_DIR: D:\a\_temp\msys64\
      QT_MSYS2_STATIC: true
      QT_MSVC: false
      QT_DEBUG: false
      GO111MODULE: off
      CGO_CFLAGS_ALLOW: ".*" 
      CGO_CXXFLAGS_ALLOW: ".*" 
      CGO_LDFLAGS_ALLOW: ".*" 
      #CGO_ENABLED: 1
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:

    - name: Install Go
      continue-on-error: true
      run: |
        curl -sL --retry 10 --retry-delay 60 -O https://dl.google.com/go/go1.16.5.windows-amd64.zip
        expand-archive -path go1.16.5.windows-amd64.zip -destinationpath .
        Move-Item -Path go -Destination C:\go-root

    - name: Setup MSYS2 and install Qt5
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw64
        install: mingw-w64-x86_64-toolchain
    - shell: msys2 {0}
      run: |
        pacman --noconfirm -S sed git mingw-w64-x86_64-qt-creator mingw-w64-x86_64-qt5-static
        pacman -Scc
        pacman -Sc

    - name: Get Qt binding for Go
      run: |
        C:\go-root\bin\go.exe get -v -tags=no_env github.com/therecipe/qt/cmd/...

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: 'akiyosi/goneovim'
        fetch-depth: 0
        path: .\src\github.com\akiyosi\goneovim

    # FIXME: Should be fixed with the deprecation of set-env
    - name: Set PATH
      run: |
        $env:PATH = "C:\\msys64\\usr\\bin;C:\\bin;C:\\go-root\\bin;$env:PATH"
        echo "::set-env name=PATH::$env:PATH"

    - uses: actions/cache@v2
      id: cache-qt-bindings-windows
      with:
        path: |
          C:\src\github.com\therecipe\qt\*
          !C:\src\github.com\therecipe\qt\.git
        key: ${{ matrix.qtversion }}-qtbindings-windows-${{ env.cache-version }}

    - name: Check dir
      run: |
        dir C:\
        dir C:\bin\
        dir D:\a\_temp\
        dir D:\a\_temp\msys64
        dir D:\a\_temp\msys64\usr
        dir D:\a\_temp\msys64\usr\bin

    # - name: Generate Qt bindings
    #   if: ${{ steps.cache-qt-bindings-windows.outputs.cache-hit != 'true' }}
    #   shell: msys2 {0}
    #   run: |
    #     /c/bin/qtsetup -test=false

    - name: Generate Qt bindings
      if: ${{ steps.cache-qt-bindings-windows.outputs.cache-hit != 'true' }}
      run: |
        C:\bin\qtsetup.exe -test=false

    - name: Get dependencies
      continue-on-error: true
      run: |
        go get -v -d github.com/akiyosi/goneovim/...

    - name: Clear Go build caches
      run: |
        C:\go-root\bin\go.exe clean -cache

    # - name: Build
    #   run: |
    #     cd ${{ github.workspace }}\src\github.com\akiyosi\goneovim\cmd\goneovim
    #     ${{ github.workspace }}\bin\qtdeploy -ldflags "-X github.com/akiyosi/goneovim/editor.Version=${{ steps.version-windows.outputs.GONEOVIM_VERSION }}"  build desktop
    #     Copy-Item ..\..\runtime -destination .\deploy\windows\ -recurse

    - name: Build
      shell: msys2 {0}
      run: |
        cd /c/src/github.com/akiyosi/goneovim/cmd/goneovim
        /c/bin/qtmoc
        /c/bin/qtdeploy build desktop

    # - name: Test
    #   shell: msys2 {0}
    #   run: |
    #     /d/a/goneovim/goneovim/go-root/bin/go test github.com/akiyosi/goneovim/editor
